version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: api-payment-postgres
    environment:
      POSTGRES_DB: ApiPaymentSystem
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - api_payment_pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: api-payment-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@api-payment-kafka:9093
    
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://api-payment-kafka:29092,EXTERNAL://PPS:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
    
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  api_payment_pgdata:
  kafka_data:
